# Generated by Django 3.1.1 on 2020-09-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
